Add files via upload

diff --git a/twres/bin/file_manager b/twres/bin/file_manager
--- a/twres/bin/file_manager
+++ b/twres/bin/file_manager
@@ -1,22 +1,26 @@
 #!/bin/bash
 
 readonly PARTITION_CONFIG_FILE="/twres/partition.txt" 
+readonly DEFAULT_START_DIRS=(
+    "/sdcard" 
+    "/external_sd" 
+    "/data"
+    "/usb-otg"
+)
 
 _items=()
 _selected_index=0
 _page_start_index=0
-stty_orig=$(stty -g)
+stty_orig="$(stty -g)"
 terminal_height=$(stty size | cut -d ' ' -f 1)
 readonly VIEW_HEIGHT=$((terminal_height - 6))
-
-
 
 flash_image_command() {
     local image_path="$1"
     local target_block="$2"
     
-    printf "flashing block with img"
-    dd if="$image_path" of="$target_block"
+    printf "Flashing block with img (dd if=\"%s\" of=\"%s\" bs=4M)\n" "$image_path" "$target_block"
+    dd if="$image_path" of="$target_block" bs=4M
 }
 
 handle_img_flash() {
@@ -65,11 +69,11 @@ handle_img_flash() {
     stty "$stty_orig"
     return 0
   fi
-
+  
   while true; do
     printf "\033c"
     printf "_FLASH IMAGE MENU \n"
-    printf "Image: %s\n" "$image_path"
+    printf "Image: %s\n" "$(basename "$image_path")"
     
     printf "Select block to flash (Only existing blocks are shown):\n"
 
@@ -87,7 +91,6 @@ handle_img_flash() {
       echo
     done
 
-    
     printf "[vol+] Up | [vol-] Down | [power] Flash | [power+vol-] Quit\n"
 
     stty -echo -icanon
@@ -95,22 +98,22 @@ handle_img_flash() {
     stty "$stty_orig"
 
     case "$flash_key" in
-      j) 
+      j)
         if [ "$_flash_selected_index" -lt "$((target_count - 1))" ]; then
           _flash_selected_index=$((_flash_selected_index + 1))
         fi
         ;;
-      k) 
+      k)
         if [ "$_flash_selected_index" -gt 0 ]; then
           _flash_selected_index=$((_flash_selected_index - 1))
         fi
         ;;
-      l | $'\r' | $'\n')
+      l | $'\r' | $'\n') 
         local selected_target="${_available_targets[_flash_selected_index]}"
         
         printf "\033c"
         printf " Executing Image Flash \n"
-        printf "Flashing %s to %s...\n" "$image_path" "$selected_target"
+        printf "Flashing %s to %s...\n" "$(basename "$image_path")" "$selected_target"
 
         flash_image_command "$image_path" "$selected_target"
         
@@ -122,8 +125,8 @@ handle_img_flash() {
         return 0
         ;;
       q)
-      exit
-      ;;
+        return 0
+        ;;
     esac
   done
 }
@@ -179,94 +182,178 @@ draw_ui() {
   done
 
   
-  printf "[vol+] Up | [vol-] Down | [power] Open/Flash | [power+vol-] Quit\n"
+  printf "[vol+] Up | [vol-] Down | [power] Flash | [power+vol-] Quit\n"
+}
+
+draw_start_menu() {
+    local menu_items=()
+    local dir
+    for dir in "${DEFAULT_START_DIRS[@]}"; do
+        if [ -d "$dir" ] && [ "$(ls -A "$dir")" ]; then
+            menu_items+=("$dir (Mounted)")
+        else
+            menu_items+=("$dir (Unmounted)")
+        fi
+    done
+    
+    local menu_count="${#menu_items[@]}"
+    local current_index=$1
+
+    printf "\033c\n"
+    printf "_Flash File Manager | Select Storage \n"
+    printf "================================================\n"
+    
+        for ((i=0; i < menu_count; i++)); do
+            item="${menu_items[i]}"
+            if [[ "$i" -eq "$current_index" ]]; then
+                printf "> \033[7m%s\033[0m\n" "$item"
+            else
+                printf "  %s\n" "$item"
+            fi
+        done
+    
+    local lines_printed="${#menu_items[@]}"
+    for (( j = lines_printed; j < VIEW_HEIGHT; j++ )); do
+            echo
+        done
+
+	printf "[vol+] Up | [vol-] Down | [power] Select | [power+vol-] Quit\n"
+}
+
+select_start_dir() {
+    local _start_selected_index=0
+    local menu_count="${#DEFAULT_START_DIRS[@]}"
+
+    while true; do
+        draw_start_menu "$_start_selected_index"
+
+        stty -echo -icanon
+        read -n 1 start_key
+        stty "$stty_orig"
+
+        case "$start_key" in
+            j)
+                if [ "$_start_selected_index" -lt "$((menu_count - 1))" ]; then
+                    _start_selected_index=$((_start_selected_index + 1))
+                fi
+                ;;
+            k)
+                if [ "$_start_selected_index" -gt 0 ]; then
+                    _start_selected_index=$((_start_selected_index - 1))
+                fi
+                ;;
+            l | $'\r' | $'\n')
+                local selected_dir="${DEFAULT_START_DIRS[_start_selected_index]}"
+                if [[ -d "$selected_dir" ]]; then
+                    cd "$selected_dir" || exit 1
+                    return 0
+                else
+                    printf "\033c"
+                    printf "WARNING: %s not found. Starting in /\n" "$selected_dir"
+                    sleep 1
+                    cd / || exit 1
+                    return 0
+                fi
+                ;;
+            q)
+                exit 0
+                ;;
+        esac
+    done
+}
+
+file_manager_main() {
+    _selected_index=0
+    _page_start_index=0
+
+    while true; do
+        get_items
+        draw_ui
+        
+        stty -echo -icanon
+        read -n 1 key
+        stty "$stty_orig"
+
+        item_count="${#_items[@]}"
+
+        case "$key" in
+            j)
+                if [ "$_selected_index" -lt "$((item_count - 1))" ]; then
+                    _selected_index=$((_selected_index + 1))
+                fi
+                if [ "$_selected_index" -ge "$((_page_start_index + VIEW_HEIGHT))" ]; then
+                    _page_start_index=$((_page_start_index + 1))
+                fi
+                ;;
+            k)
+                if [ "$_selected_index" -gt 0 ]; then
+                    _selected_index=$((_selected_index - 1))
+                fi
+                if [ "$_selected_index" -lt "$_page_start_index" ]; then
+                    _page_start_index=$((_page_start_index - 1))
+                fi
+                ;;
+
+            ' ')
+                next_start=$((_page_start_index + VIEW_HEIGHT))
+                if [ "$next_start" -lt "$item_count" ]; then
+                    _page_start_index="$next_start"
+                    _selected_index=$((_page_start_index))
+                fi
+                ;;
+            b)
+                if [ "$_page_start_index" -gt 0 ]; then
+                    _page_start_index=$((_page_start_index - VIEW_HEIGHT))
+                    if [ "$_page_start_index" -lt 0 ]; then 
+                        _page_start_index=0
+                    fi
+                    _selected_index=$((_page_start_index))
+                fi
+                ;;
+
+            h)
+                cd .. || exit 1
+                _selected_index=0
+                _page_start_index=0
+                ;;
+            l | $'\r' | $'\n')
+                selected_item_raw="${_items[_selected_index]}"
+                selected_item="${selected_item_raw%/}" 
+
+                if [[ "$selected_item" == *.img ]] && [[ -f "$selected_item" ]]; then
+                    full_path="$(pwd)/$selected_item" 
+                    handle_img_flash "$full_path"
+
+                elif [[ "$selected_item" == *.zip ]] && [[ -f "$selected_item" ]]; then
+                    full_path="$(pwd)/$selected_item" 
+                    
+                    printf "\033c" 
+                    printf " Executing TWRP Install \n"
+                    printf "Command: twrp install \"%s\"\n" "$full_path"
+                    
+                    twrp install "$full_path"
+                    
+                    printf "\n Press any key to return to the file manager \n"
+                    
+                    stty -echo -icanon
+                    read -n 1 wait_key
+                    stty "$stty_orig"
+                
+                elif [[ -d "$selected_item" ]]; then
+                    cd "$selected_item" || exit 1
+                    _selected_index=0 
+                    _page_start_index=0
+                fi
+                ;;
+            q)
+                exit 0
+                ;;
+        esac
+    done
 }
 
 trap 'stty "$stty_orig"; printf "\033c"' EXIT INT TERM
 
-while true; do
-  get_items
-  draw_ui
-  
-  stty -echo -icanon
-  read -n 1 key
-  stty "$stty_orig"
+select_start_dir
 
-  item_count="${#_items[@]}"
-
-  case "$key" in
-    j)
-      if [ "$_selected_index" -lt "$((item_count - 1))" ]; then
-        _selected_index=$((_selected_index + 1))
-      fi
-      if [ "$_selected_index" -ge "$((_page_start_index + VIEW_HEIGHT))" ]; then
-        _page_start_index=$((_page_start_index + 1))
-      fi
-      ;;
-    k)
-      if [ "$_selected_index" -gt 0 ]; then
-        _selected_index=$((_selected_index - 1))
-      fi
-      if [ "$_selected_index" -lt "$_page_start_index" ]; then
-        _page_start_index=$((_page_start_index - 1))
-      fi
-      ;;
-
-    ' ')
-      next_start=$((_page_start_index + VIEW_HEIGHT))
-      if [ "$next_start" -lt "$item_count" ]; then
-        _page_start_index="$next_start"
-        _selected_index=$((_page_start_index))
-        if [ "$_selected_index" -ge "$item_count" ]; then
-            _selected_index=$((item_count - 1))
-        fi
-      fi
-      ;;
-    b)
-      if [ "$_page_start_index" -gt 0 ]; then
-        _page_start_index=$((_page_start_index - VIEW_HEIGHT))
-        if [ "$_page_start_index" -lt 0 ]; then 
-            _page_start_index=0
-        fi
-        _selected_index=$((_page_start_index))
-      fi
-      ;;
-
-    h)
-      cd .. || exit 1
-      _selected_index=0
-      _page_start_index=0
-      ;;
-    l | $'\r' | $'\n')
-      selected_item_raw="${_items[_selected_index]}"
-      selected_item="${selected_item_raw%/}" 
-      full_path="$(pwd)/$selected_item" 
-
-      if [[ "$selected_item" == *.img ]] && [[ -f "$selected_item" ]]; then
-        handle_img_flash "$full_path"
-
-      elif [[ "$selected_item" == *.zip ]] && [[ -f "$selected_item" ]]; then
-        
-        printf "\033c" 
-        printf " Executing TWRP Install \n"
-        printf "Command: twrp install \"%s\"\n" "$full_path"
-        
-        twrp install "$full_path"
-        
-        printf "\n Press any key to return to the file manager \n"
-        
-        stty -echo -icanon
-        read -n 1 wait_key
-        stty "$stty_orig"
-      
-      elif [[ -d "$selected_item" ]]; then
-        cd "$selected_item" || exit 1
-        _selected_index=0 
-        _page_start_index=0
-      fi
-      ;;
-    q)
-      exit
-      ;;
-  esac
-done
+file_manager_main
